#include<linux/module.h>
#include<linux/fs.h>
#include<linux/uaccess.h>
#include<linux/wait.h>
#include<linux/workqueue.h>
#include<linux/timer.h>
#include<linux/kthread.h>
#include<linux/delay.h>


#define DEVICE_NAME "mydevice"

static int major;
static char kbuf[100];
static int data_ready =0;

static wait_queue_head_t wq;
static struct work_struct my_work;
static struct timer_list my_timer;
static struct task_struct *my_thread;

/*-----------------------WORKQUEUE-------------------------*/
static void work_handler(struct work_struct *work)
{
	pr_info("Workqueue: Generating data\n");
	snprintf(kbuf,sizeof(kbuf), "Data generated by driver\n");
	data_ready=1;
	wake_up_interruptible(&wq);
}
static void timer_callback(struct timer_list *t)
{
 pr_info("ISR: Timer interrupt occurred\n");
 schedule_work(&my_work);
}
/*---------------------ISR(TIMER)-----------------------*/
static ssize_t my_write(struct file *file, const char __user *buf, size_t len, loff_t *off)
{
	char temp[50];
	if(copy_from_user(temp,buf,len))
		return -EFAULT;
        pr_info("User request: %s\n",temp);
	/*Simulate interrupt after 2 sec*/
	mod_timer(&my_timer, jiffies + msecs_to_jiffies(2000));

	return len;
}

/*----------------------Read--------------------------*/

static ssize_t my_read(struct file *file, char __user *buf,size_t len, loff_t *off)
{
	pr_info("Read:waiting for data........\n");
	wait_event_interruptible(wq,data_ready == 1);
	data_ready=0;
	
	if(copy_to_user(buf,kbuf,strlen(kbuf)+1))
		return -EFAULT;
	return strlen(kbuf)+1;
}

/*-------------------Kernel Thread--------------------*/
static int thread_fn(void *data)
{
  while(!kthread_should_stop())
  {
	pr_info("Kernel thread running.......\n");
	ssleep(5);
  }
  return 0;
}

/*-------------------FOPS-----------------------------*/
static struct file_operations fops={
	.owner = THIS_MODULE,
	.write=my_write,
	.read = my_read,
};
/*-----------------INIT------------------------------*/

static int __init my_init(void)
{
 major=register_chrdev(0,DEVICE_NAME,&fops);
 init_waitqueue_head(&wq);
 INIT_WORK(&my_work, & work_handler);
 timer_setup(&my_timer,timer_callback,0);
 my_thread = kthread_run(thread_fn, NULL, "my_kthread");
 pr_info("Driver loaded: major = %d\n", major);

 return 0;
}

/*-------------------EXIT-------------------------*/
static void __exit my_exit(void)
{
 add_timer(&my_timer);
 flush_work(&my_work);

 if(my_thread)
	 kthread_stop(my_thread);
 unregister_chrdev(major,DEVICE_NAME);
 pr_info("Driver unloaded\n");
}

module_init(my_init);
module_exit(my_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Nandini");
MODULE_DESCRIPTION("Simple taskq,waitq,workq working together");
